---
httpx_max_keepalive_connections: 5
httpx_max_connections: 20
use_fast: true
use_batched_tokenization: true
chunk_size: 3000
chunk_overlap: 512
api_url: http://localhost:8000/v1
api_key: empty
model_identifier: jondurbin/airoboros-l2-70b-3.1.2
max_tokens: 1000
temperature: 0.2
